@baseUrl= http://localhost:8000/api/v1/users



### Testing API

### User
### GetUser

GET {{baseUrl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzbWl0YTEyQGdtYWlsLmNvbSIsImlhdCI6MTc4MDQ4MjE1NSwiZXhwIjoxNzgwNDgyMjE1fQ.cvNe9bnGr5P-n8bkjwMUYQG60c7whcBuP2pCXpAu_Oo

### POST new user

POST  {{baseUrl}}
Content-Type: application/json

{
    "name": "asmaita12",
    "email": "asmita12@gmail.com",
    "password":"123"
}


### login  user

POST  {{baseUrl}}/login
Content-Type: application/json

{

    "email": "asmita12@gmail.com",
    "password":"123"
}