@baseUrl= http://localhost:8000/api/v1



### Testing API

### User
### GetUser

GET {{baseUrl}}
Authorization: eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzbWl0YTEyQGdtYWlsLmNvbSIsImlhdCI6MTc4MDU1OTEwMCwiZXhwIjoxNzgwNjQ1NTAwfQ.3A1GhyE7a6bA2yGCGX8INdG6E5RZU_4Eog6zdUN_NDw

### POST new user

POST  {{baseUrl}}/users
Content-Type: application/json

{
    "name": "asmaita12",
    "email": "asmita12@gmail.com",
    "password":"123"
}


### login  user

POST  {{baseUrl}}/users/login
Content-Type: application/json

{

    "email": "asmita12@gmail.com",
    "password":"123"
}


### Transactions: all private routers

### Post new transacitons
POST {{baseUrl}}/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFzbWl0YTEyQGdtYWlsLmNvbSIsImlhdCI6MTc4MDU1OTEwMCwiZXhwIjoxNzgwNjQ1NTAwfQ.3A1GhyE7a6bA2yGCGX8INdG6E5RZU_4Eog6zdUN_NDw

{
    "type":"income",
    "title": "Salary",
    "amount": 2345,
    "tdate": "2-3-2024"

}